import type { Metadata } from "next";
import "./globals.css";
import { Ubuntu } from 'next/font/google'
import Navbar from "@/components/home-page/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700"],
  variable: '--ubuntu',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={ubuntu.className}
      >

        {children}
      </body>
    </html>
  );
}
